def sample_responses(input_text):
    user_message = str(input_text).lower()
    text = input_text
    if user_message in ("help", "/help"):
        return "Hi, just send a message and the bot will reply with the one that's going to bypass the algorithms \nFor more info contact me on through my website \nhttps://ahmad-fawzy.com/"
    if user_message in ("about", "/about"):
        return "This bot was fully programmed and made by Ahmad Fawzy \nWebsite https://ahmad-fawzy.com/"
    if user_message in ("supported_languages", "/supported_languages"):
      return 'This bot helps you to get around Instagram and Facebook comment filters, allowing you to simply hate and insult people who deserve it as much as you want without the fear of being restricted or banned. The bot currently supports "English, Arabic, Persian, French, German, Spanish, Portuguese, Irish, and Dutch"'
    for i in range(len(text)):
        text = text.replace('a', 'а')
        text = text.replace('b', 'Ꮟ')
        text = text.replace('c', 'с')
        text = text.replace('d', 'ԁ')
        text = text.replace('e', 'е')
        text = text.replace('f', '𝐟')
        text = text.replace('g', 'ġ')
        text = text.replace('h', 'һ')
        text = text.replace('i', 'і')
        text = text.replace('j', 'ј')
        text = text.replace('k', 'κ')
        text = text.replace('l', 'ӏ')
        text = text.replace('m', 'ⅿ')
        text = text.replace('n', 'ո')
        text = text.replace('o', 'օ')
        text = text.replace('p', 'р')
        text = text.replace('q', 'զ')
        text = text.replace('r', '𝗋')
        text = text.replace('s', 'ѕ')
        text = text.replace('t', '𝗍')
        text = text.replace('u', 'ս')
        text = text.replace('v', 'ν')
        text = text.replace('w', '𝗐')
        text = text.replace('x', 'х')
        text = text.replace('y', 'у')
        text = text.replace('z', 'ʐ')
        text = text.replace('أ', 'ا')
        text = text.replace('ب', 'ٮ࣭')
        text = text.replace('ث', 'ٮٌْ')
        text = text.replace('ت', 'ٮࣼ')
        text = text.replace('ج', 'ح')
        text = text.replace('ح', 'ح')
        text = text.replace('خ', 'حْ')
        text = text.replace('د', 'د')
        text = text.replace('ذ', 'دْ')
        text = text.replace('ر', 'ر')
        text = text.replace('ز', 'رْ')
        text = text.replace('س', 'س')
        text = text.replace('ش', 'سٌْ')
        text = text.replace('ص', 'ص')
        text = text.replace('ض', 'صْ')
        text = text.replace('ط', 'ط')
        text = text.replace('ظ', 'طْ')
        text = text.replace('ع', 'ع')
        text = text.replace('غ', 'عْ')
        text = text.replace('ف', 'ڡْ')
        text = text.replace('ق', 'ٯٌ')
        text = text.replace('ك', 'ک')
        text = text.replace('ل', 'ل')
        text = text.replace('ن', 'ںْ')
        text = text.replace('ه', 'ه')
        text = text.replace('و', 'و')
        text = text.replace('ي', 'ى̤')
        text = text.replace('ئ', 'ى')

    return text
